export enum LoginPage {
  loginForm = '#login-form',
  registerSection = '.op-a-register',
  email = '#email',
  username = '#username',
  password = '#password',
  usernameAdmin = '#mod-login-username',
  passwordAdmin = '#mod-login-password',

  loginButton = '#submit-login-form',
  confirmPassword = '#password2', 
  forgotYourPassword ='.container-fluid > .row > .col-md-6 > .font-weight-bold',
  nextButton ='#emailForm > .form-group > .btn',
  verificationCodeMsg= '.pb-3',
  refreshdeploy= `.swal2-confirm`,
  emailtextbox='#email',
  newpassword='#newPassword',
  confirmnewpassword='#confirmPassword',
  resetpassbutton='#resetpassword',
  successfulrestpass='app-subscriber > .notifier__container > ul > .notifier__container-list > .notifier__notification > .notifier__notification-message',
  cancelflownotification='app-subscriber > .notifier__container > ul > .notifier__container-list > .notifier__notification > .notifier__notification-button',
  nextbuttonforgotpass='#emailForm > .form-group',
  nextforgetbtn='#confirmForm > .form-group > .btn',
  emailrequiredmessage='.link-blue',
  verificationcodetextbox='#token',
  nextbuttonverificationcode='#confirmForm > .form-group',
  verificationcoderequiredmsg='.link-blue',
  superuservalidationmsg='.link-blue',
  passwordnotmatch='.form-text > div',
  refreshpopup = '.swal2-confirm',
  
  }

export enum RegistrationPage {
  registerButton = '#register-to-bid',
  email = '#email',
  username = '#username',
  password = '#password',
  confirmPassword = '#password2',
  mobileNumber = '.iti > .form-control',
  billingName='#billing-name',
  billingAddress='#billing-address',
  state='#state', 
  city='#city',
  pincode='#pin-zip-code',
  country='#country',
  submit = '#submit',
  notification = '.notifier__notification-message',
  bidderApproval='.font-weight-bold.pt-1',
  verify='.mt-2',
  cancelNotification='app-subscriber > .notifier__container > ul > .notifier__container-list > .notifier__notification > .notifier__notification-button > .notifier__notification-button-icon',
  invalidemailidMsg = '.link-blue',
  emailErrorMsg =':nth-child(1) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  invalidconformPassword =':nth-child(2) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  reference ='#if-you-have-participated-in-any-auctions-in-the-past-please-share-the-name-of-the-auction-house-and-place-of-auction',
  inValidMobileNumber ='.col-sm-4 > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  billErrorMsg =':nth-child(7) > .row > .col-sm-4 > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  billAddressErrorMsg ='.col-sm-8 > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  stateErrorMsg = ':nth-child(8) > .row > :nth-child(1) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback',
  cityErrorMsg = ':nth-child(2) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  pincodeErrorMsg = ':nth-child(10) > .row > :nth-child(2) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message',
  notificationExistEmailId ='.notifier__notification-message',
  error=':nth-child(9) > .row > :nth-child(1) > formly-wrapper-form-field.ng-star-inserted > .form-group > .invalid-feedback > formly-validation-message'
 }

export enum Homepage {
  username = '.row > .nav-item > .nav-link',
  profile = `.row > .nav-item > .dropdown-menu > [href='/profile']`,
  logout ='.row > .nav-item > .dropdown-menu > [href="/logout"]',
  registerbutton=':nth-child(2) > div > .text-white',
  }

export enum Mailinator {
  search = '#search',
  go = 'GO',
  findEmail = 'table.table-striped.jambo_table tr td',
  json = '#pills-json-tab',
  emailBody = 'pre',
  inboxPanel = '#inbox_pane',
  dataTable = 'div.wrapper-primary-table',
}

export enum YOPmail{
  search='#login',
  arrow='#refreshbut > .md > .material-icons-outlined',
  findemail='main.yscrollbar>div#mailctn>div#mail>div>p:nth-Child(3)',
  bodyemail='#ifmail',
  subscribelink='main.yscrollbar>div#mailctn>div#mail>div>p>a:nth-child(1)',
  absenteebidmail='main.yscrollbar>div#mailctn>div#mail>div>p:nth-child(2)',
  absenteebidmail1='main.yscrollbar>div#mailctn>div#mail>div>p:nth-child(3)',
  absenteebidbulkmail='main.yscrollbar>div#mailctn>div#mail>div>div>div>div>span>b:nth-child(1)',
  auctionlive='main.yscrollbar>div#mailctn>div#mail>div>div>div>span>b:nth-child(1)',
  refresh='#refresh',
  lotmsgresults='main.yscrollbar>div#mailctn>div#mail>div>p:nth-child(4)'
}

export enum ProfilePage {
  registertoBid = '.btn > .ng-star-inserted',
  bidderRegPending = '.font-weight-bold.pt-1',
  edit='.font-500 > .fas',
  username = '.row > .nav-item > .nav-link',
  profile = `.row > .nav-item > .dropdown-menu > [href='/profile']`,
  editDetails ='body',
  approvalPendingsecondMessage ='.text-small', 
  phone = '.iti > .form-control',
  billName = '#billing-name',
  billingAddress ='#billing-address',
  country = '#country',
  city='#city',
  disableButton='.pb-3.ng-invalid > div[_ngcontent-serverapp-c122=""]',
  topUserName ='.nav-link > .font-600',
  topUserNameCompare ='.pb-3 > :nth-child(3) > :nth-child(2) > h5',
  submitButton = '#submit',
  selectprofile='#navbarCollapse > links > div > div > div > a:nth-child(2)',
  email=`h5[class='d-inline']`,
  logout='#logout'
  }

export enum CommonChecks {
  haveText = 'have.text',
  haveLength = 'have.length',
  show = 'show',
  beVisible = 'be.visible',
  notBeVisible = 'not.be.visible',
  haveClass = 'have.class',
  greater = 'be.gt',
  greaterEqual = 'be.gte',
  lower = 'be.lt',
  lowerEqual = 'be.lte',
  equal = 'eq',
  haveCss='have.css',
  backgroundColor='background-color',  
}

export enum GeneralLocators {
  body = 'body',
  ajaxSpinner = '#ajax_spinner',
  path = '../fixtures',
  outerHeight = 'outerHeight',
}

export enum Menu {
  departments = ':nth-child(1) > .nav-link',
  depitem1 = `a.dropdown-item:contains('{submenu}')`,
  departmentsbreadcrum = `.active > .fs-14:contains('{submenubreadcrum}')`,
  editorial = '.pr-2 > .nav-link',
  editpage = '.h2-font-size',
  auction = ':nth-child(3) > .nav-link',
  auctionmenu = `a.dropdown-item:contains('{auctionsubmenu}')`,
  allauction = `h1.font-weight-bold.auc-title:contains('{allauctionsubmenu}')`,

  moremenu = ':nth-child(4) > .nav-link',
  moresubmenu = `a.dropdown-item:contains('{submenu}')`,
  about = `h1:contains('{aboutcontact}')`,
  }

  export enum Footer {
    departments = '.col-lg-4 > .mb-4',
    modernIndianFineArts = '.col-lg-4 > .item0',
    contemporaryIndianFineArts = '.col-lg-4 > .item1',
    vintageClassicAutomobiles ='.col-lg-4 > .item2',
    indianAsianAntiquities ='.col-lg-4 > .item3',
    antiquarianBookPrints ='.col-lg-4 > .item4',
    photography = '.col-lg-4 > .item5',
    indianFilmMemorabilia = '.col-lg-4 > .item6',
    hollywoodWorldFilmMemorabilia = '.col-lg-4 > .item7',
    footballCricketOther = '.col-lg-4 > .item8',
    auction = '.col-lg-2 > :nth-child(1) > .text-white',
    allAuction = '.col-lg-2 > [href="/home/auctions"]',
    currentAuction = '.col-lg-2 > [href="/home/auctions?status=current"]', 
    upcommingAuction = '.col-lg-2 > [href="/home/auctions?status=upcoming"]', 
    archiveAuction = '.col-lg-2 > [href="/home/auctions?status=archived"]',
    company = ':nth-child(3) > .mt-4', 
    aboutUs = ':nth-child(3) > [href="/pages/about"]',
    editorial = ':nth-child(3) > [href="/pages/editorial"]',
    legal=':nth-child(4) > .mt-4',
    termsandconditions=':nth-child(4) > :nth-child(3) > .footer-link',
    termsofuse=':nth-child(5) > .footer-link',
    privacypolicy=':nth-child(4) > .footer-link',
    consigningToAuctions='.col-lg-2 > :nth-child(7)',
    contactUs = '.col-lg-2 > :nth-child(6) > .text-white',
    delivery = '.col-lg-2 > :nth-child(8)',
    clientRelations ='.col-lg-2 > :nth-child(9)',
    artistResaleRoyalty ='.col-lg-2 > :nth-child(10)',
    careerf = '.col-lg-2 > :nth-child(10)',
    help='[href="/pages/help"] > .text-white'
  }

export enum liveauction{
  newviewalllink =`.container.pb-3 > .ng-star-inserted > .row > :nth-child(2) > .fs-18`,
  newviewalllink1=`#allauctions`,
  viewallauction = ':nth-child(1) > .ng-star-inserted > .row > :nth-child(2) > .fs-15',
  guestbid = `div.fs-18.font-weight-bold`,
  stagelive = `//*[text()='D&I.{auctionNumber}']//following::span[text()=' Auction Live ']`,
  stageresult = `//*[text()='D&I.{auctionNumber}']//following::span[text()=' Auction Results ']`,
  auctionnumber = `div.fs-16.font-weight-bold:contains('{number}')`,
  lotpage = `div.fs-20.pb-2`,
  registerbutton = `#lot-1 > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .btn`,
  bidform = `h1.font-weight-bold.pb-3`,
  bidbutton1='#lot-1 > .mx-c > #register-to-bid > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex > .btn',
  bidbutton = ` #lot-1 > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex`,
  bidplace = `:nth-child(1) > .w-100 > .btn`,
  viewdetails = `#lot-1 > .min-ht > app-lot-information.ng-star-inserted a.viewbtn`,
  detailpagebutton = `a.btn.text-white.text-nowrap.text-center.font-weight-bold.fs-14.bg-blue.float-right.w-100.ng-star-inserted`,
  detailpagebidbutn = `.d-flex > .btn`,
  detailplacebid = `:nth-child(1) > .w-100 > .btn`,
  selfAbsenteeBid ='#lot-2 > .mx-c > .filter-close-revise-btn > :nth-child(1) > .ng-star-inserted > .hyperlink-text',
  selfAbsenteeBidDetail=':nth-child(2) > .hyperlink-text',
  selfAbsenteeBidLot ='#lot-17 > .justify-content-md-center > a > .lot-list-grid-img',
  selfAbsenteeBidClosedLot='#lot-2 > .justify-content-md-center > a > .lot-list-grid-img',
  auctionvalidation = `div.font-600.fs-20:contains('{number}')`,
  validation = 'div.font-600.fs-20',
  registerpagevalidation = 'body > app-root > div > div > div > div > app-sign-up > div > h4.fs-22.font-weight-bold.mb-0.ng-star-inserted',
  nextbidtext = `#lot-{lotNumber} > .mx-25 > .d-flex > .text-left > .text-muted`,
  nextbidrupee = `#lot-{lotNumber} > .mx-25 > .d-flex > .text-left > .font-weight-bold`,
  nextbiddollar = `#lot-{lotNumber} > .mx-25 > .d-flex > .text-left > .mb-0`,
  currentbidtext = `#lot-{lotNumber} > .mx-25 > .pb-md-0 > a > .ng-star-inserted > .text-muted`,
  currentbidrupee=`#lot-{lotNumber} > .mx-25 > .pb-md-0 > a > .ng-star-inserted > .font-weight-bold`,
  currentbiddollar=`#lot-{lotNumber} > .mx-25 > .pb-md-0 > a > .ng-star-inserted > :nth-child(3)`,
  estimatetext = `#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .font-gray`,
  estimaterupee=`#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .text-dark > .font-weight-bold`,
  estimatedollar=`#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .text-dark > .ng-star-inserted`,
  totalbidtext = `#lot-{lotNumber} > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .pl-0 > .boder-right > div > .font-500`,
  totalbidcount = `#lot-1 > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .pl-0 > .boder-right > div > .font-weight-bold`,
  lottimersection = `#lot-{lotNumber} > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .text-right > div.ng-star-inserted > .text-muted`,
  lottimer = `#lot-1 > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .text-right > div.ng-star-inserted > :nth-child(2) > .font-weight-bold > .ng-star-inserted`,
  nextbidamount = `#lot-1 >.mx-25 > .d-flex > .text-left > .font-weight-bold`,
  currentbidamount = `#lot-1 > .mx-25 > .pb-md-0 > a > .ng-star-inserted > .font-weight-bold`,
  detailcurrentbidtext = `.col-sm-4 > .ng-star-inserted > :nth-child(1)`,
  detailcurrentbidrupee='.col-sm-4 > .ng-star-inserted > .font-weight-bold',
  detailcurrentbiddollar='.col-sm-4 > .ng-star-inserted > h6',
  detailestimatetext = `.col-sm-8 > :nth-child(1)`,
  detailestimaterupee = `.pl-0 > .ng-star-inserted > .font-weight-bold`,
  detailestimatedollar='.col-sm-8 > .ng-star-inserted',
  detailnextbidtext = `app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .ng-star-inserted > .text-dark`,
  detailnextbidrupee = `.pl-0 > .ng-star-inserted > .font-weight-bold`,
  detailnextbiddollar='.pl-0 > .ng-star-inserted > h6',
  lotclosesintextindetailpage = `.text-right > .mr-1`,
  detailpagelotclosestimer = `.text-right > .font-weight-bold > .ng-star-inserted`,
  nextbutton = `.next-prev-btn.mobile-hide > :nth-child(2) > :nth-child(2)`,
  previousbutton = `.next-prev-btn.mobile-hide > :nth-child(2) > :nth-child(1)`,
  artistcolumn = `.tabular-header > :nth-child(1) > :nth-child(3)`,
  livetoggle = `.tabular-view-btn.ng-star-inserted`,
  listpageregisterbutton = `:nth-child(1) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .btn`,
  textsearch = `body > app-root > div > div > div > div > app-auction`,
  listdetail = `:nth-child(1) > :nth-child(3) > .viewbtn`,
  listbidbutton = `:nth-child(1) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex > .btn`,
  listplacebid = `:nth-child(1) > .w-100 > .btn`,
  savebuttoncolor = `#save-18095`,
  mylotspage = `#view-my-lot`,
  selectauction =`select`,
  mylotbid = `:nth-child(5) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .justify-content-end > .col-12 > .btn`,
  mylotbidBidnowbutton = `:nth-child(1) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .justify-content-end > .col-12 > .btn`,
  mylotbid1=':nth-child(2) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .justify-content-end > .col-12 > .btn',
  mylotbid7=':nth-child(7) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .justify-content-end > .col-12 > .btn',
  colorxpath = `//*[@id="save-18095"]/i`,
  artisttoggle = `.tabular-header > :nth-child(1) > :nth-child(3)`,
  placebidmylot = `//button[contains(text(),'Place Bid')]`,
  mylotestimatesrupee = `:nth-child(1) > .card > :nth-child(1) > .row > .text-dark > .font-weight-bold`,
  mylotestimatesdollar=`:nth-child(1) > .card > :nth-child(1) > .row > .text-dark > :nth-child(3)`,
  mylotcurrentbidrupee = `:nth-child(1) > .card > :nth-child(1) > .row > .pl-2 > .auction-bg1 > div.font-weight-bold > .font-weight-bold`,
  mylotcurrentbiddollar= `:nth-child(1) > .card > :nth-child(1) > .row > .pl-2 > .auction-bg1 > :nth-child(3) > h5`,
  mylotnextbidrupee = `:nth-child(1) > .card > :nth-child(1) > .row > .pr-2 > .auction-bg1 > div.font-weight-bold > .font-weight-bold`,
  mylotnextbiddollar=`:nth-child(1) > .card > :nth-child(1) > .row > .pr-2 > .auction-bg1 > :nth-child(4) > h5`,
  mylotnextbidtext = `:nth-child(1) > .card > :nth-child(1) > .row > .pr-2 > .auction-bg1 > .text-muted`,
  mylotcurrentbidtext= `:nth-child(1) > .card > :nth-child(1) > .row > .pl-2 > .auction-bg1 > :nth-child(1)`,
  mylotestimatestext = `:nth-child(1) > .card > :nth-child(1) > .row > .text-dark > h5`,
  livewithresulttab = `#livewithresult`,
  supertotalbids = `#lot-1 > .mx-c > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .pl-0 > .boder-right > .cursor-pointer > .font-500`,
  lotclosedselfabsentee='#lot-{lotNumber} > .mx-25 > .col-sm-4 > a > .badge-primary',
  resultauctionvalidation = `div.font-weight-bold.fs-20:contains('{number}')`,
  resultvalidation = 'div.font-weight-bold.fs-20',
  lottabresults='#lots',
  resultselfabsenteebid='#lot-1 > .mx-c > .filter-close-revise-btn > :nth-child(1) > .ng-star-inserted > .hyperlink-text',
  closeselfabsenteebidpopup='.close',
  liveStatus='#auction_stage_label',
  myabsenteebidtxt='#register-to-bid > div > div > a',
  myabsenteebidvalue='#totalAbsenteeBid > div > div > div.modal-body.bid_history-modal.pl-pr-0.ng-star-inserted > div.row.pt-2.pb-2.bg-white.ng-star-inserted > div.col-lg-5.col-4 > h5',
  lotclosedfordryrun=':nth-child(2) > .d-flex > .font-weight-bold',
  bidbuttonsellprice='#lot-2 > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex',
  bidbuttonreservedry='#lot-4 > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex'

  
}

export enum Subscriber{
  cookiebutton = '.cc-allow',
  subscriptionform = `.form-control`,
  submit = `button.subscribe-button`,
  verify = `.mt-2`,
  refreshbutton='.swal2-confirm',
  displayverified = `body > app-root > app-footer > footer > div > div > div:nth-child(4) > div.subscribe-box > app-subscriber > notifier-container > ul > li > notifier-notification > p`,
  displayveri='app-subscriber > .notifier__container > ul > .notifier__container-list > .notifier__notification > .notifier__notification-message',
  notificationverified='app-subscriber > .notifier__container > ul > .notifier__container-list > .notifier__notification > .notifier__notification-message',
}

export enum Viewallauctions{
  viewall = ':nth-child(1) > .ng-star-inserted > .row > :nth-child(2) > .fs-15',
  allauctions = ':nth-child(1) > .ng-star-inserted > .row > :nth-child(1) > .font-weight-bold',
  listview='.float-right',
  image=':nth-child(1) > :nth-child(2) > .w-115 > .auction-list-img',
  saveauction=`(//*[text()='{auctionNumber}']//following::div//app-jlike//div//div//i)`,
  viewdetailslot='#lot-{lotNumber} > div.min-ht > app-lot-information > div > app-arts > div > div > div:nth-child(1) > div.col-9.pl-pr-5 > a > div > a.viewbtn',
  savelots='#save-6893 > .fa',
  viewmyauction='.overview-follow-container > .btn',
  auctionname=`div.fs-16.font-weight-bold:contains('{auctionNumber}')`,
  viewmylots='.overview-follow-container > .btn',
  savelots1='#save-4405 > .fa',
  lotname='.font-weight-bold.pt-1.ng-star-inserted',
  lotnum='.lotno-info.pt-3.pl-3.pr-3', 
  lotname1='#lot-{lotNumber} > app-lot-information > div > app-books > div > div > div:nth-child(2) > div > a > div.pt-1.mt-1 > a',
  gridview='.background-green',
  title='.tabular-header > tr > :nth-child(3)',
  auctionnum=':nth-child(2) > :nth-child(1) > a.ng-star-inserted > .fs-12',
  auction_name=`#auction_id_345 > :nth-child(1) > a.ng-star-inserted > .fs-14 > .badge-primary:contains('{auctionNumber}')`, 
  lotTitle='#lot-{lotnumber} >.min-ht > app-lot-information.ng-star-inserted a.fs-16.font-600.text-dark',
  savelot='#save-7349 > .fa',
  savelot1='#save-7348 > .fa',
  saveauctionxpath=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
  selectauctionviewall='#auctions',
  gotoauctionviewall='.go-to-auction-btn',
  cookiebuttonAccept = '.cc-allow',
  auctionlistview='#list-gird-view',
  auctiongridview='#list-gird-view',
  liveStageName='.link-blue a-status',
}

export enum MyAuction{
  profilename='.nav-link > .font-600',
  myauction='.row > .nav-item > .dropdown-menu > [href="/myauctions"]',
  auclistview='.float-right > path',
  listview='.float-right',
  gridview='.float-right',
  lotopen=`:nth-child(12) > :nth-child(1) > .ng-star-inserted > .fs-12:contains('{auctionNumber}')`
}

export enum MyLots{
  mylots='.row > .nav-item > .dropdown-menu > [href="/mylots"]',
  gotoauction='.go-to-auction-btn',
  gotoauction1='#go-to-auction',
  selectauction='#auctions',
  viewdetails=':nth-child(1) > .card > :nth-child(1) > .lotno-info > :nth-child(1) > .viewbtn',
  listviewlot='.toggleViews-btns > .float-right',
  lotlistview='.float-right',
  lotlistview1=`div#list-gird-view.toggleViews-btns`,
  mylottitle='.tabular-lot-artist',
  lotnum='#lot-{lotnumber} app-root > div > div > div > div > app-my-lots > app-grid-list > div > div > div.ng-star-inserted > div > div:nth-child(2) > a > div.lotno-info > div.font-weight-bold.pt-1.ng-star-inserted',
}

export enum OpenforConsignment{
  openconsignment=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Open For Consignment ']`,
  OpenforConsignmenttext='.link-blue',
  saveauctionconsign=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
}

export enum ClosedforConsignment{
  closeconsignment=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Closed for Consignment ']`,
  ClosedforConsignmenttext='.link-blue',
  saveauctioncloseconsign=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
}

export enum AuctionHighlights{
  auctionhighlights=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Auction Highlights ']`,
  auctionhighlightstext='.pb-2 > .link-blue',
  highlightstext='#highlights',
  saveauctionhighlight=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
}

export enum CatelogueUploaded{
  catelogueuploaded=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Catalogue Uploaded ']`,
  catelogueuploaded1='.pb-2 > .link-blue',
  saveauctionCatelogueUploaded=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
  stageNameVarification='.pb-2 > .link-blue',
  closingSchedule='#result',
  closingonResult='.nav-item > #result',
  lotNo='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.fs-16',
  auctionStartIn='.auction_start_box > .fs-17',
  viewDetails='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.viewbtn',
  artistname='#lot-{lotNumber} > div.min-ht > app-lot-information > div > app-arts > div > div > div:nth-child(2) > div > a > div > a',
  lotTitle='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.text-dark',
  mediamDate='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted > [_ngcontent-serverapp-c76=""] > app-arts.ng-star-inserted > :nth-child(1) > .pt-3 > :nth-child(2) > .col-sm-12 > .fs-14 > a > :nth-child(1)',
  size='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted > [_ngcontent-serverapp-c76=""] > app-arts.ng-star-inserted > :nth-child(1) > .pt-3 > :nth-child(2) > .col-sm-12 > .fs-14 > a > .mt-1 > .mb-0',
  rupeeOnResult='#lot-{lotNumber} > .mx-25 > :nth-child(1) > a > .text-dark > .font-weight-bold',
  dollarOnResult='#lot-{lotNumber} > .mx-25 > :nth-child(1) > a > .text-dark > :nth-child(2)',
  gdpOnResult='#lot-{lotNumber} > .mx-25 > :nth-child(1) > a > .text-dark > :nth-child(3)',
  resultWin='#lot-{lotNumber} > .mx-25 > .text-md-center > .winning-bid',
  resultSold='#lot-{lotNumber} > .mx-25 > .text-md-right > .anchor-status-badge > .badge-primary',
  extension='#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .font-gray',
  rs='#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .text-dark > .font-weight-bold',
  dollar='#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .text-dark > :nth-child(2)',
  gdp='#lot-{lotNumber} > .mx-25 > .col-sm-8 > a > .text-dark > :nth-child(3)',
  imageOnDetail='.ngx-gallery-image',
  saveButton='.float-md-right > div.ng-star-inserted > #save-24506 > .fa',
  previousbutton='.pl-md-3 > .fixed-next-prev-buttons > .next-prev-btn > div > .ml-0',
  nextbutton='.pl-md-3 > .fixed-next-prev-buttons > .next-prev-btn > div > :nth-child(2)',
  breadcrum='.active > .fs-14',
  lotTileDetail='.pb-2 > .pt-1',
  lotnoDetail='.col-sm-11 > .font-600',
  artistnameDetails='.fs-26.mr-1',
  mediamDateDetail='.lot-captions-scrollable-section > :nth-child(1) > .font-weight-bold',
  mediamDateDetailPage='.lot-captions-scrollable-section > :nth-child(1) > :nth-child(2)',
  signaturetitle='.lot-captions-scrollable-section > :nth-child(2) > .font-weight-bold',
  signatureValue='.lot-captions-scrollable-section > :nth-child(2) > :nth-child(2)',
  sizeTitle='.lot-captions-scrollable-section > :nth-child(3) > .font-weight-bold',
  sizeValue='.lot-captions-scrollable-section > :nth-child(3) > .ng-star-inserted',
  winPrice='.winning-bid > div > .font-weight-bold',
  soldStatus='div.ng-star-inserted > div > .text-dark',
  winResult='.winning-bid > .pt-1',
  estimateTitle='.col-sm-8 > :nth-child(1)',
  estimaterupee='.col-sm-8 > .font-weight-bold',
  estimatedoller='.col-sm-8 > :nth-child(3)',
  estimategdp='.col-sm-8 > :nth-child(4)',
  startPrice='#lot-{lotNumber} > .mx-25 > .col-sm-4 > a > .text-dark > .font-weight-bold', 
  dollerStartPrice='#lot-{lotNumber} > .mx-25 > .col-sm-4 > a > .text-dark > :nth-child(2)',
  gbpStartPrice='#lot-{lotNumber} > .mx-25 > .col-sm-4 > a > .text-dark > .ng-star-inserted',
  abseneteeBidButton='#lot-{lotNumber} > .mx-c > #register-to-bid button.bg-blue',
  nextAbsenteeBid='#lot-{lotNumber} > .mx-c > #register-to-bid input#bidValue',
  nextAbsenteeBidDetail=':nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
  abseneteeBidButtonDetail=':nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue',
  bidnowbutton='#lot-{lotNumber} > .mx-c > #register-to-bid > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex > .btn'
}

export enum PrivatePreview{
  privatepreview=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Private Preview ']`,
  privatepreview1='.pb-2 > .link-blue',
  saveauctionPrivatePreview=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
}

export enum AuctionResults{
  auctionresults=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Auction Results ']`,
  auctionresults1='.pb-2 > .link-blue',
  listviewlotresult=':nth-child(2) > .right-arrow',
  image='.pl-4',
  lotTab='#lots',
  adminSelfabsentee='#lot-2 > .mx-c > .filter-close-revise-btn > :nth-child(1) > .ng-star-inserted > .hyperlink-text',
  printbutton='.d-md-inline > svg > path',
  lotprice=':nth-child(2) > :nth-child(3) > .ng-star-inserted',
  totalRow='table.table-condensed tr',
  sellPrice='table.table-condensed tr:nth-child(${i}) td:nth-child(5) h5',
  pricelot=`table.table-condensed tr:nth-child({j}) td:nth-child(5) h5`,
  sellprice=`table.table-condensed tr:nth-child({k}) td:nth-child(4) h5`,
  value=`//h4[text()=' Selling Price (Inclusive of Margin) ']//following::h4[{x}]`,
  price=`table.table-condensed tr:nth-child({i}) td:nth-child(4) h5`,
  lotsoldpercent='tr > :nth-child(2) > div > .text-muted',
  totalsale='tr > :nth-child(1) > :nth-child(1) > .font-weight-bold',
  totalsaleusd='tr > :nth-child(1) > :nth-child(1) > :nth-child(2)',
  table='table.auctio-result-list-view',
  lotno='thead > tr > :nth-child(1)',
  totalrow='table.table-condensed>tbody>tr',
  toplot1=':nth-child(1) > .row > :nth-child(3) > .font-weight-bold > .ml-3',
  toplot2=':nth-child(2) > .row > :nth-child(3) > .font-weight-bold > .ml-3',
  toplot3=':nth-child(3) > .row > :nth-child(3) > .font-weight-bold > .ml-3',
  price1=`table.table-condensed tr:nth-child({i}) td:nth-child(5) h5`,
  sellpricepreview=`table.table-condensed tr:nth-child({k}) td:nth-child(5) h5`,
  printButton='.d-md-inline > img',
  assumingUS ='#print-section > :nth-child(1) > :nth-child(3)',
  assumingGBP =':nth-child(1) > .fs-14.ng-star-inserted',
  totalsaleResult=':nth-child(1) > div > .text-muted',
  lotsSold='tr > :nth-child(2) > div > .text-muted',
  sellingPrice=':nth-child(3) > .text-muted',
  resultInRupee='tr > :nth-child(1) > :nth-child(1) > .font-weight-bold',
  lotsoldPercent='tr > :nth-child(2) > div > :nth-child(2)',
  resultLotImage=':nth-child(1) > .card > .img-hight-200',
  lotNumber=':nth-child(1) > .card > .des-cover > .m-0 > .p-0 > .p',
  artistname=':nth-child(1) > .card > .des-cover > :nth-child(2) > .ng-star-inserted > .font-weight-bold',
  auctionName=':nth-child(1) > .card > .des-cover > :nth-child(2) > .ng-star-inserted > .fs-14',
  estimates=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .pr-0 > .font-gray',
  estimaterupee=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .pr-0 > :nth-child(2) > .fs-16',
  estimatedo=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .pr-0 > :nth-child(2) > :nth-child(2)',
  estimategdp=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .pr-0 > :nth-child(2) > :nth-child(3)',
  winner=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .text-md-left > .winning-bid',
  sold=':nth-child(1) > .card > .des-cover > .pb-2 > .for-desktop-view > .text-md-right > .badge-position1 > :nth-child(1) > .ng-star-inserted > .font-weight-bold'
 

}

export enum AbsenteeBidCloseLotList{
  absenteeBidClose=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Absentee Bidding Closed ']`,
  absenteeBidClose1='.pb-2 > .link-blue',
  auctionname='.fs-40',
  listviewlotabsenteeclose='.tabular-view-btn > .float-right',
  save='#save-360 > .ng-star-inserted > .fa',
  nextlot='.pl-md-3 > .fixed-next-prev-buttons > .next-prev-btn > div > :nth-child(2)',
  saveabsenteebidclose=`//*[text()='{auctionNumber}']//following::div//app-jlike`,
  lotTitleabsenteebidclose='#lot-{lotnumber} > app-lot-information > div > app-arts > div > div > div:nth-child(2) > div > a > div > a',
  savelotabsenteebidclose='#lot-{savelot} > app-lot-information > div div div button > i',
  lotname='.pt-1',
  yourabsenteebid='#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(1) > div.ng-star-inserted > .mb-0',
  auctionstarttime='div.float-md-right > .fs-17',
  mylotsfilter='#my-lot',
  lotnamemylotfilter='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.viewbtn',
  alllots='.ml-3',
  savecolor='#save-23663 > span.ng-star-inserted > .fa',
  gotolot='.input-group > .form-control',
  arrowsymbol='#go-to-lot',
  viewdetails='#lot-{lotNumber} > app-lot-information > div > app-books > div > div > div:nth-child(1) > div.col-9 > a > div > a.viewbtn',
  rupeeamountlotlist='#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(1) > div.ng-star-inserted > .font-weight-bold',
  dollaramountlotlist='#lot-{lotNumber} > .px-2 > #register-to-bid > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(1) > div.ng-star-inserted > .fs-14',
  listviewmylotpage='.float-right > path'
  }

  export enum AbsenteeBidCloseViewDetails{
    registertobid='#lot-1 > .px-2 > .filter-close-revise-btn > :nth-child(1) > div.ng-star-inserted > div > .btn',
    lotdetails='#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.viewbtn',
    yourabsenteebiddetails='.d-none > .row > :nth-child(1) > div.ng-star-inserted > .mb-0',
    rupeeamount='.d-none > .row > :nth-child(1) > div.ng-star-inserted > .font-weight-bold',
    dollaramount='.d-none > .row > :nth-child(1) > div.ng-star-inserted > .fs-12',
    starttimedetails='.d-none > .row > .text-right > .text-m-white > .mb-0',
  }

  export enum AbsenteeBidCloseMyLot{
    yourabsenteebidmylot=':nth-child(5) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(2) > :nth-child(1) > .mb-0',
    rupeeamountmylot=':nth-child(5) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(2) > :nth-child(1) > .font-weight-bold',
    dollaramountmylot=':nth-child(5) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > :nth-child(2) > :nth-child(1) > .fs-14',
    gotoauctionmylot='.go-to-auction-btn'
  }

  export enum Backendlogin{
    username='#mod-login-username',
    password='#mod-login-password',
    login='.btn-group > .btn',
    loginform='#element-box', 
    errormsg='.alert-message',
    admindashboard='.page-title',
    userMenu=':nth-child(2) > [href="#"]',
    userManagement='.open > .scroll-menu > :nth-child(1) > .dropdown-toggle',
    newButton='#toolbar-new > .btn', 
    accountDetails='.active > a',
    accessUserGroup='#myTabTabs > :nth-child(2) > a',
    basicSetting='#myTabTabs > :nth-child(3) > a',
    fields='#myTabTabs > :nth-child(4) > a',
    registerToBid='#myTabTabs > :nth-child(6) > a',
    billingDetails='#myTabTabs > :nth-child(7) > a',
    reference=':nth-child(8) > a',
    last=':nth-child(9) > a',
    save='#toolbar-apply > .btn',
    nameErrormsg='.alert > :nth-child(3)',
    loginNameErrormsg='.alert > :nth-child(4)',
    emailErrormsg='.alert > :nth-child(5)',
    whatappErrormsg='.alert > :nth-child(6)',
    billErrormsg='.alert > :nth-child(7)',
    billaddressErrormsg='.alert > :nth-child(8)',
    countryErrormsg='.alert > :nth-child(9)',
    stateErrormsg='.alert > :nth-child(10)',
    pinErrormsg='.alert > :nth-child(11)',
    agreeErrormsg='.alert > :nth-child(12)',
    formname='#jform_name',
    formLogin='#jform_username',
    formPassword='#jform_password',
    formConformPasword='#jform_password2',
    formEmail='#jform_email',
    bidderACL=':nth-child(10) > .controls > .checkbox',
    supperUserACL=':nth-child(12) > .controls > .checkbox',
    derivazUser=':nth-child(5) > .controls > .checkbox',
    whatappNumber='#jform_com_fields_whatsapp_number',
    billName='#jform_com_fields_billing_name',
    billingAddress='#jform_com_fields_billing_address',
    country='#jform_com_fields_country',
    state='#jform_com_fields_state',
    city='#jform_com_fields_city',
    pin='#jform_com_fields_pin_zip_code',
    termcondition='#jform_com_fields_terms_conditions0',
    searchbox='#filter_search',
    searchIcone='.input-append > .btn',
    searchUsername='.name > a',
    saveClose='#toolbar-save > .btn',
    saveNew='#toolbar-save-new > .btn',
    closedButton='#toolbar-cancel > .btn',
    userCheckbox='tr > :nth-child(1) > .hasTooltip',
    userDelete='#toolbar-delete > .btn',
    disableUser=':nth-child(4) > .btn > .icon-publish',
    enableUser='.row0 > :nth-child(4) > .btn',
    selectuser='#cb0',
    selectBidder=':nth-child(10) > .controls > .checkbox',

  }

  export enum Backendlots{
    componentsMenu=':nth-child(5) > [href="#"]',
    auctionMenu='.scroll-menu > :nth-child(2) > .no-dropdown',
    lotMenu='#submenu > :nth-child(2) > a',
    lotDetails='#myTabTabs > :nth-child(1) > a',
    lotDescription ='#myTabTabs > :nth-child(2) > a',
    lotFields='#myTabTabs > :nth-child(3) > a',
    filteredFields='#myTabTabs > :nth-child(4) > a',
    nameErrormsgLot='.alert > :nth-child(3)',
    startDateLot='.alert > :nth-child(4)',
    endDateLot='.alert > :nth-child(5)',
    extendedDateLot='.alert > :nth-child(6)',
    lotTitle='#jform_title',
    startDate='#jform_start_date',
    endDate='#jform_end_date',
    extendedDate='#jform_extended_date', 
    clickAuction='#first_name_group > .controls',
    selectAuction ='#jform_auction_id_chzn > .chzn-single > span',
    enterselectAuction='#jform_auction_id_chzn > .chzn-drop > .chzn-search',
    dateErromsg='.alert-error > :nth-child(10)',
    extendedDateerror='.alert-error > :nth-child(11)',
    startPrice='#jform_start_price',
    reservePrice='#jform_reserve_price',
    lotDescriptionField ='#jform_description',
    DateofArtwork ='#jform_com_fields_dateofartwork',
    Signature ='#jform_com_fields_signature',
    clickatplus='[style="width:8%;"] > .btn-group > .btn',
    Height='#jform_com_fields__sizecm__sizecm0__Height',
    Width='#jform_com_fields__sizecm__sizecm0__Width',
    YearofArtwork='#jform_com_fields_year',
    Medium='#jform_com_fields_medium',
    lowerestimate='#jform_estimate_low',
    higherestimate='#jform_estimate_high',
    lowerestimateusd='#jform_estimate_low_usd',
    higestestimateusd='#jform_estimate_high_usd',
    lowershouldbesmall='.alert-error > :nth-child(7)',
    selectAuctionOption='#jform_auction_id_chzn > .chzn-single > span',
    image='div#jform_lot_image_modal>table>tbody>tr>td:nth-child(2) input',
    selectImage='#jform_lot_image_button',
    savemodulePopup='.save-modal-data',
    searchauctiononlot='#filter_search',
    searchsymbollot='.input-append > .btn',
    searchtoollot='.hidden-phone > .btn',
    selectauctintitle='#filter_auction_name_chzn > a > span',
    statelot='#filter_state_chzn > a > span',
    selectlotstatuslot='#filter_sold_status_chzn > a > span',
    selectauctintitledropdwn='#filter_auction_name_chzn > .chzn-single > div > b',
    searchauctiontitle='#filter_auction_name_chzn > .chzn-drop > .chzn-search > .active',
    searchauctionlot='.active-result',
    searchauctionlotresults=':nth-child(1) > :nth-child(4) > :nth-child(2) > small',
    statedropdwnlot='#filter_state_chzn > .chzn-single > span',
    publishstatelot='#filter_state_chzn > div > ul > li:nth-child(2)',
    trashstatelot='#filter_state_chzn > div > ul > li:nth-child(3)',
    lotstatusdrop='#filter_sold_status_chzn > .chzn-single > span',
    upcominglot='#filter_sold_status_chzn > div > ul > li:nth-child(2)',
    livelot='#filter_sold_status_chzn > div > ul > li:nth-child(3)',
    soldlot='#filter_sold_status_chzn > div > ul > li:nth-child(4)',
    broughtinlot='#filter_sold_status_chzn > div > ul > li:nth-child(5)',
    withdrawn='#filter_sold_status_chzn > div > ul > li:nth-child(6)',
    clearbtnlot='.js-stools-container-bar > :nth-child(4) > .btn',
    searchauctionlotform='#jform_auction_id_chzn > div > div > input[type=text]',
    lotnumtxtbox='#jform_lot_number',
    ishighlight='[for="jform_is_highlighted0"]',
    fieldstab='#myTabTabs > :nth-child(3) > a',
    filterstab='#myTabTabs > :nth-child(4) > a',
    descriptiontab='#myTabTabs > :nth-child(2) > a',
    toggle=':nth-child(1) > .controls > .js-editor-tinymce > .toggle-editor > .btn-group > .btn',
    lotsubtitlelot='#jform_com_fields_lotsubtitle',
    setoflot='#jform_com_fields_setof',
    mins=':nth-child(4) > .btn-group > .btn-danger > .icon-minus',
    savebtnlot='#toolbar-apply',
    alertmsglot='.alert-message',
    saveclostlot=`//button[normalize-space()='Save & Close']`,
    savenewlot=`//button[normalize-space()='Save & New']`,
    closelot=`//button[@class='btn btn-small button-cancel']`,
    searchlotclick=':nth-child(4) > :nth-child(1) > a',
    lotchkbox='#cb0',
    trashbtnlot='#toolbar-trash', 
    dryrunSaveNew='#toolbar-save-new > .btn',
    selectDryrunAuction='#jform_status',
    selectartist='#jform_artsit_id_chzn > .chzn-single > span',
    searchartistlotform='#jform_artsit_id_chzn > div > div > input[type=text]',
    selectsearchartist='#jform_artsit_id_chzn > div > ul > li > em'
  }

  export enum LotcreateCSVImport{
    csvimportbtn='#toolbar-custom > .btn',
    choosefile='#sbox-content > :nth-child(1) > .form-inline > :nth-child(1) > .actions > input',
    importcsv='#sbox-content > :nth-child(1) > .form-inline > :nth-child(1) > .actions > .btn',
    alertmsglotcsv='.alert > :nth-child(4)',
    trashlot='#toolbar-trash > .btn',
    selectalllots='#lotsList > thead > tr > th.hidden-phone > input[type=checkbox]'

  }
  
  export enum AbsenteeBidOpen{
    absenteeBidOpen=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Absentee Bidding Open ']`,
    absenteeBidClose=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Absentee Bidding Closed ']`,
    catelogeUploaded=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Catalogue Uploaded ']`,
    auctionlive=`//*[text()='D&I.{auctionNumber}']//following::span[text()=' Auction Live ']`,
    registertobidabsenteeopen='#lot-{lotNumber} > .w-100.pb-2 > .filter-close-revise-btn > :nth-child(1) > div.ng-star-inserted > div > .btn',
    lotnumabsenteebidopen='#lot-{lotNumber} > app-lot-information.ng-star-inserted > [_ngcontent-serverapp-c78=""] > app-arts.ng-star-inserted > :nth-child(1) > .pt-3 > :nth-child(1) > .col-9 > :nth-child(1) > .ng-star-inserted > .fs-16',
    loginlink='.pb-2.ng-star-inserted > .hyperlink-text',
  }

  export enum AbsenteeBidOpenlotdetails{
    lotlistview='.fs-40',
  }

export enum Switchuser {
profilename = `.nav-link > .font-600`,
buttonlogin = `:nth-child(3) > .btn`
}

export enum Absenteebidopenstage 
{
  registerbutton = `#lot-1 > .px-2 > .filter-close-revise-btn > :nth-child(1) > div.ng-star-inserted > div > .btn`,
  estimatetext=`#lot-1 > .mx-25 > .col-sm-8 > a > .font-gray`,
  estimaterupee='#lot-1 > .mx-25 > .col-sm-8 > a > .text-dark > .font-weight-bold',
  estimatedollar='#lot-1 > .mx-25 > .col-sm-8 > a > .text-dark > .ng-star-inserted',
  startingbidtext = `#lot-1 > .mx-25 > .col-sm-4 > a > .text-muted`,
  startingbidsection = `#lot-1 > .mx-25 > .col-sm-4 > a`,
  placeabsenteebutton = `#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue`,
  incrementbutton = `#lot-1 > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .form-group > .increase-icon`,
  bidvalue = `#lot-1 > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .form-group > #bidValue`,
  successfullAbsenteeBidPlacedMesssage = `.notifier__notification-message`,
  cancelmessage='.notifier__notification-button',
  deletebid = `#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > :nth-child(1)`,
  notificationcancelbutton = `.notifier__notification-button`,
  listviewbidbutton = `:nth-child(2) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue`,
  listdeletebutton = `:nth-child(2) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > .text-right.ng-star-inserted > .col-12.ng-star-inserted > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > :nth-child(1)`,
  revisebutton = `#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > .ml-1`,
  increaseamount = `#lot-{lotNumber} > .px-2 > .filter-close-revise-btn > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .form-group > .increase-icon`,
  lotdetailpagelink = `#lot-{lotNumber} > .min-ht > app-lot-information.ng-star-inserted a.viewbtn`,
  lotdetailpreviousbutton = `.pl-md-3 > .fixed-next-prev-buttons > .next-prev-btn > div > .ml-0`,
  detailguestregisterbutton = `app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(2) > .btn`,
  estimatesdetailtext = `.col-sm-8 > :nth-child(1)`,
  detailestimatesection = `.bid-scrollable-section > :nth-child(3) > :nth-child(1)`,
  detailsestimaterupee=`.col-sm-8 > .font-weight-bold`,
  detailsestimatedollar=`.col-sm-8 > .ng-star-inserted`,
  detailpagestartbidtext = `.col-sm-4 > .ng-star-inserted > :nth-child(1)`,
  detailstartbidrupee = `.col-sm-4 > .ng-star-inserted > .font-weight-bold`,
  detailstartbiddollar=`.ng-star-inserted > h6`,
  deletedetailpage = `.d-none > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > :nth-child(1)`,
  revisedetailpage = `.d-none > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > .ml-1`,
  placeabsenteedetailpage = `:nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue`,
  successabsenteebidverification = `.notifier__notification-button`,
  increaseamountdetailpagebutton = `.d-none > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .form-group > .increase-icon`,
  savebuttonab = `#save-25186`,
  viewmylotbutton = `.overview-follow-container > .btn`,
  estimatestextmylot = `:nth-child(1) > .card > :nth-child(1) > .row > .fs-16 > h5`,
  mylotestimatesrupee = `:nth-child(1) > .card > :nth-child(1) > .row > .fs-16 > .font-weight-bold`,
  mylotestimatesdollar=`:nth-child(1) > .card > :nth-child(1) > .row > .fs-16 > :nth-child(3)`,
  mylotstartingbid = `:nth-child(1) > .card > :nth-child(1) > .row > .text-md-right > .mt-1`,
  mylotstartingbidamountrupee = `:nth-child(1) > .card > :nth-child(1) > .row > .text-md-right > .font-weight-bold`,
  mylotstartingbidamountdollar=`:nth-child(1) > .card > :nth-child(1) > .row > .text-md-right > h4.mb-0`,
  placeabsenteebuttonmylot = `:nth-child(1) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue`,
  mylotdeletebidbutton = `:nth-child(1) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > :nth-child(1)`,
  absenteebidvalue = `.p-1.ng-star-inserted > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) :nth-child(2) > :nth-child(1) > :nth-child(1)`,
  mylotrevise = `:nth-child(1) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > .ml-1`,
  mylottoggle = `.float-right.cursor-pointer.hyperlink-text.ng-star-inserted`,
  imagecolumnheader = `.pl-4`,
  mylotlistviewplaceabsenteebidbutton = `:nth-child(1) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > :nth-child(2) > div > .bg-blue`,
  mylotlistviewdeletebutton = `:nth-child(1) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(3) > .canbtn > .cupa-dropdownlist-top > #bid-form > .canrev-btn > :nth-child(1)`,
  mylotincrementamount = `:nth-child(1) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > .row > .col-12 > .canbtn > .cupa-dropdownlist-top > #bid-form > .form-group > .increase-icon > .fa`,
  bidamount='#bidValue',
  incrementbtngridview='#lot-5 > .mx-c > #register-to-bid > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .increase-icon',
  decreasebtngridview=`#lot-5 > .mx-c > #register-to-bid > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .decrease-icon`,
  bidamountgridview='#lot-5 > .mx-c > #register-to-bid > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
  incrementbtnlistview=':nth-child(5) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .increase-icon',
  decreasebtnlistview=':nth-child(5) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .decrease-icon',
  bidamountlistview=':nth-child(5) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
  incrementbtndetails=':nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .increase-icon',
  decreasebtndetails=':nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .decrease-icon',
  bidamountdetails=':nth-child(2) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
  incrementbtnmylotpagegrid=':nth-child(3) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .cupa-dropdownlist-top > #bid-form > .position-relative > .increase-icon',
  decreasebtnmylotpagegrid=':nth-child(3) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .cupa-dropdownlist-top > #bid-form > .position-relative > .decrease-icon',
  bidamountmylotgrid=':nth-child(3) > .card > .pb-1 > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
  incrementbtnmylotpagelist=':nth-child(3) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .increase-icon',
  decreasebtnmylotpagelist=':nth-child(3) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > .decrease-icon',
  bidamountmylotlist=':nth-child(3) > .tabular-absentee-btn > app-lot-actions > :nth-child(1) > :nth-child(1) > :nth-child(1) > div.w-100 > .cupa-dropdownlist-top > #bid-form > .position-relative > #bidValue',
}

export enum Livewithresult
{
  login = `.mr-3 > .text-dark`,
  profileregistereduser = `.font-weight-bold.pt-1`,
  lottitlelink = `#lot-1 > :nth-child(2) > .hyperlink-text > h5.font-weight-bold > .fs-14`,
  highestbiddercolumn = `.tabular-header > tr > :nth-child(9)`,
  livepagelottitle = `#lot-1 > :nth-child(2) > .hyperlink-text > h5.font-weight-bold > .fs-14 > span`,
  livetodetailpagepreviousbutton = `.pl-md-3 > .fixed-next-prev-buttons > .next-prev-btn > div > .ml-0`,
  stagevalidation = `#print-section > :nth-child(1) > :nth-child(1) > .fs-20`,
  bidbuttonvalue = `#lot-1 > :nth-child(10) > app-lot-actions > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex > .btn > .font-weight-bold`,
  hightestbid=`#lot-1 > :nth-child(10) > app-lot-actions > :nth-child(1) > :nth-child(1) > .row > .col-md-12 > .d-flex`,
  placebidbutton = `:nth-child(1) > .w-100 > .btn`,
  currentbidamount = `#lot-1 > :nth-child(5) > .ng-star-inserted`,
  nextbidamount = `#lot-1 > :nth-child(6)`,
  prevbidcount = `#lot-1 > td.live-result-total-bid > app-lot-actions > div.ng-star-inserted > h5`,
  highestbiddername = `#lot-1 > :nth-child(9)`,
  columnheaders = `body > app-root > div > div > div > div > app-liveandresult > div:nth-child(2) > div > div > div.pt-2.pb-2 > table > thead > tr`
}

export enum BackendAuctionCreation
{
  componentsmenu='#menu > li:nth-child(5) > a',
  auctionmenu='.scroll-menu > :nth-child(2) > .no-dropdown',
  auctionNewbutton='#toolbar-new > .btn',
  basicdetails='.active > a',
  notification='#myTabTabs > :nth-child(2) > a',
  highlightpreview='#myTabTabs > :nth-child(3) > a',
  param='#myTabTabs > :nth-child(4) > a',
  financialinfo='#myTabTabs > :nth-child(5) > a',
  saveauction='#toolbar-apply > .btn',
  titleerror='#system-message-container > div > div:nth-child(3)',
  auctionnameerror='#system-message-container > div > div:nth-child(4)',
  startdateerror='#system-message-container > div > div:nth-child(5)',
  enddateerror='#system-message-container > div > div:nth-child(6)',
  auctionimgerror='#system-message-container > div > div:nth-child(7)',
  auctionnumerror='#system-message-container > div > div:nth-child(8)',
  inrerror='#system-message-container > div > div:nth-child(9)',
  aucformtitle='#jform_title',
  aucformname='#jform_name',
  aucformstartdate='#jform_start_date',
  aucformenddate='#jform_end_date',
  aucformimg='#jform_auction_image',
  aucformnumber='#jform_auction_number',
  aucstatus='#jform_state',
  aucdatetimeinfo='#jform_date_time_informtaion',
  aucresultinfo='#jform_result_fields',
  aucwinnername='[for="jform_show_winnername0"]',
  aucclosingschedule='[for="jform_is_dynamic_closing_schedule0"]',
  aucnotificationtab='#myTabTabs > :nth-child(2) > a',
  aucsndaucstartnotification='#jform_send_auction_start_notification > label:nth-child(2)',
  aucnotifywinner='#jform_notify_winners > label:nth-child(2)',
  aucnotifylooser='#jform_notify_loosers > label:nth-child(2)',
  aucnotifyabsenteebidopen='#jform_notify_absentee_open > label:nth-child(2)',
  aucnotifyresult='#jform_notify_result > label:nth-child(2)',
  auchighlightpreviewtab='#myTabTabs > :nth-child(3) > a',
  auchighlightcarouselselect='#jform_highlights_carousel_button',
  modalpop='div#jform_highlights_carousel_modal>table>tbody>tr>td:nth-child(2) input',
  assertpath='#jform_highlights_carousel_table > thead > tr > :nth-child(2)',
  addhighlightimage='#jform_highlights_carousel_table > .ui-sortable > tr > :nth-child(5) > .btn-group > .add',
  savemodalpopup='#jform_highlights_carousel_modal > .modal-footer > .save-modal-data',
  auchighlighttopselect='#jform_highlights_top_button',
  modalpopuphighlighttop='div#jform_highlights_top_modal>table>tbody>tr>td:nth-child(2) input',
  asserthighlighttoppath='#jform_highlights_top_table > thead > tr > :nth-child(2)',
  addhighlighttopimage='#jform_highlights_top_table > .ui-sortable > tr > :nth-child(5) > .btn-group > .add > .icon-plus',
  savemodalpopuphighlighttop='#jform_highlights_top_modal > .modal-footer > .save-modal-data',
  aucpreviewcarouselselect='#jform_preview_carousel_button',
  modalpopuppreview='div#jform_preview_carousel_modal>table>tbody>tr>td:nth-child(2) input',
  assertpreviewpath='#jform_preview_carousel_table > thead > tr > :nth-child(2)',
  addpreviewimage='#jform_preview_carousel_table > .ui-sortable > tr > :nth-child(5) > .btn-group > .add > .icon-plus',
  savemodalpopuppreview='#jform_preview_carousel_modal > .modal-footer > .save-modal-data',
  aucpreviewtopselect='#jform_preview_top_button',
  assertpreviewtoppath='#jform_preview_top_table > thead > tr > :nth-child(2)',
  modalpopuppreviewtop='div#jform_preview_top_modal>table>tbody>tr>td:nth-child(2) input',
  addpreviewtopimage='#jform_preview_top_table > .ui-sortable > tr > :nth-child(5) > .btn-group > .add > .icon-plus',
  savemodalpopuppreviewtop='#jform_preview_top_modal > .modal-footer > .save-modal-data',
  aucpreviewbottomselect='#jform_preview_bottom_button',
  assertpreviewbottompath='#jform_preview_bottom_table > thead > tr > :nth-child(2)',
  modalpopuppreviewbottom='div#jform_preview_bottom_modal>table>tbody>tr>td:nth-child(2) input',
  addpreviewbottomimage='#jform_preview_bottom_table > .ui-sortable > tr > :nth-child(5) > .btn-group > .add > .icon-plus',
  savemodalpopuppreviewbottom='#jform_preview_bottom_modal > .modal-footer > .save-modal-data',
  aucparamtab='#myTabTabs > :nth-child(4) > a',
  auccurrencyrateinr='#jform_params__currency_rates__INR',
  auccurrencyrategbp='#jform_params__currency_rates__GBPTOINR',
  aucfinancialinfotab='#myTabTabs > :nth-child(5) > a',
  aucincrement='#jform_increment',
  aucbuyerspremium='#jform_buyers_premium',
  searchbox='#filter_search',
  searchsymbol='.input-append > .btn',
  searchtool='.hidden-phone > .btn',
  auctionnamedropdwn='#filter_name_chzn > .chzn-single > div > b',
  auctionnamefilter='#filter_name',
  nameinput='#filter_name_chzn > .chzn-drop > .chzn-search > .active',
  searchresult='em',
  firstname='#filter_name > option:nth-child(3)',
  aucname='#filter_name_chzn > a > span',
  aucnumber='#filter_auction_number_chzn > a > span',
  aucselectcategory='#filter_catid_chzn > a > span',
  selectcategorydropdwn='#filter_catid_chzn > .chzn-single > span',
  aucmodernindianartcat='#filter_catid_chzn > div > ul > li:nth-child(2)',
  aucconindianfineartcat='#filter_catid_chzn > div > ul > li:nth-child(3)',
  aucvinclasscat='#filter_catid_chzn > div > ul > li:nth-child(4)',
  aucindianasincat='#filter_catid_chzn > div > ul > li:nth-child(5)',
  aucantibookcat='#filter_catid_chzn > div > ul > li:nth-child(6)',
  aucphotocat='#filter_catid_chzn > div > ul > li:nth-child(7)',
  aucindianfilmcat='#filter_catid_chzn > div > ul > li:nth-child(8)',
  auchollywoodcat='#filter_catid_chzn > div > ul > li:nth-child(9)',
  aucfootballcat='#filter_catid_chzn > div > ul > li:nth-child(10)',
  aucstate='#filter_state_chzn > a > span',
  statedropdwn='#filter_state_chzn > .chzn-single > span',
  aucpublishstate='#filter_state_chzn > div > ul > li:nth-child(2)',
  aucunpublishstate='#filter_state_chzn > div > ul > li:nth-child(3)',
  aucdraftstate='#filter_state_chzn > div > ul > li:nth-child(4)',
  auctrashstate='#filter_state_chzn > div > ul > li:nth-child(5)',
  aucstage='#filter_status_chzn > a > span',
  stagedropdwn='#filter_status_chzn > .chzn-single > span',
  aucopenconsignstage='#filter_status_chzn > div > ul > li:nth-child(2)',
  auccloseconsignstage='#filter_status_chzn > div > ul > li:nth-child(3)',
  auchighlightstage='#filter_status_chzn > div > ul > li:nth-child(4)',
  auccatuploadstage='#filter_status_chzn > div > ul > li:nth-child(5)',
  aucpripreviewstage='#filter_status_chzn > div > ul > li:nth-child(6)',
  aucabostage='#filter_status_chzn > div > ul > li:nth-child(7)',
  aucabcstage='#filter_status_chzn > div > ul > li:nth-child(8)',
  auclivestage='#filter_status_chzn > div > ul > li:nth-child(9)',
  aucresultstage='#filter_status_chzn > div > ul > li:nth-child(10)',
  aucpostauctionstage='#filter_status_chzn > div > ul > li:nth-child(11)',
  aucarchivedstage='#filter_status_chzn > div > ul > li:nth-child(12)',
  aucnumberdropdwn='#filter_auction_number_chzn > .chzn-single > span',
  aucnumberinput='#filter_auction_number_chzn > .chzn-drop > .chzn-search > .active',
  clearbutton='#j-main-container > div > div:nth-child(1) > div.js-stools-container-bar > div:nth-child(4) > button',
  aucchkbox='#cb0',
  aucunpublishbtn='#toolbar-unpublish > button',
  aucalertmsg='.alert-message',
  aucpublishbtn='#toolbar-publish > button',
  serachauctionname=':nth-child(5) > :nth-child(1) > a',
  savebutton='#toolbar-apply > .btn',
  saveclosebutton='#toolbar-save > .btn',
  savenewbutton='#toolbar-save-new > .btn',
  cancelbutton='#toolbar-cancel > .btn',
  auctrashbtn='#toolbar-trash > .btn', 
  checkboaForAll='thead > tr > :nth-child(2) > input',
  clickStatus='#filter_state_chzn > .chzn-single > div > b',
  emptyTrash='#toolbar-delete > .btn'
}

export enum Visualtest{
  editorialsection = `.album > .container`,
  loginsection = `body > app-root > div > div > div > div > app-account > div > app-login > div > div > div`,
  loginfullbodypage = `.app-body`,
  signupimage = `.active > .homepage-slide-container`,
  signupfullpage = `app-sign-up.ng-star-inserted`,
  footer = `app-footer > .non-printable`,
  moremenu = `:nth-child(4) > .nav-link`,
  aboutusmenu = `.dropdown-menu > [href="/pages/about"]`,
  contactusmenu = `.dropdown-menu > [href="/pages/contact-us"]`,
  aboutuspage = `app-article.ng-star-inserted`,
  contactuspage = `app-article.ng-star-inserted`,
  termandcondition = '.album > .container',
  privacypolicy ='.album > .container',
  termsofUse='.album > .container',
  header ='.fixed-top > .container'
}

export enum BackendAuctionReport{
  auctionreport='#submenu > :nth-child(7) > a',
  auctionnumberreport='thead > tr > :nth-child(1)',
  auctionnamereport='thead > tr > :nth-child(2)',
  auctionstartdatereport='thead > tr > :nth-child(3)',
  auctionenddatereport='thead > tr > :nth-child(4)',
  auctioncategoryreport='thead > tr > :nth-child(5)',
  auctionbuyerspremiumreport='thead > tr > :nth-child(6)',
  auctiontotallotsreport='thead > tr > :nth-child(7)',
  auctionidreport='thead > tr > :nth-child(8)',
  auctionclick='tr > :nth-child(2) > a',
  auctionreportlotid='thead > tr > :nth-child(16)',
  searchaucnamereport='tr > :nth-child(2) > a',
  auciontotlotreport='tr > :nth-child(7) > a',
}

export enum BackendLotReport{
  lotreport='#submenu > :nth-child(8) > a',
  lottitlereport=':nth-child(2) > .js-stools-column-order',
  lotauctiontitlereport='thead > tr > :nth-child(3)',
  lotstartpricereport='[width="10%"] > .js-stools-column-order',
  lotuserreport='[width="17%"] > .js-stools-column-order',
  lotbidamountreport=':nth-child(6) > .js-stools-column-order',
  lotbiddatereport=':nth-child(7) > .js-stools-column-order',
  lotsoldreport=':nth-child(8) > .js-stools-column-order',
  lotestimatelowreport='thead > tr > :nth-child(9)',
  lotestimatehighreport=':nth-child(10) > .js-stools-column-order',
  lotstartdatereport='thead > tr > :nth-child(11)',
  lotselectuser='#filter_user_name_chzn > a > span',
  lotselectauctiontitle='#filter_auction_name_chzn > a > span',
  lotstate='#filter_state_chzn > a > span',
  lotselectlotstatus='#filter_sold_status_chzn > a > span',
  lotselectuserdropdwn='#filter_user_name_chzn',
  lotuserinput='#filter_user_name_chzn > .chzn-drop > .chzn-search > .active',
  lotsearchbyuser='em',
  lotselectaucdropdwn='#filter_auction_name_chzn > .chzn-single > span',
  lotselectauction='#filter_auction_name_chzn > div > div > input',
  lottrashstate='#filter_state_chzn > div > ul > li:nth-child(3)',
  lotstatusdropdwn='#filter_sold_status_chzn > .chzn-single > span',
  lotupcomingstatus='#filter_sold_status_chzn > div > ul > li:nth-child(2)',
  lotlivestatus='#filter_sold_status_chzn > div > ul > li:nth-child(3)',
  lotsoldstatus='#filter_sold_status_chzn > div > ul > li:nth-child(4)',
  lotbroughtinstatus='#filter_sold_status_chzn > div > ul > li:nth-child(5)',
  lotwithdrawnstatus='#filter_sold_status_chzn > div > ul > li:nth-child(6)',
  lotclearbutton=':nth-child(4) > .btn',
  lottotalrow='table.table.table-striped.table-hover>tbody>tr'
}

export enum backendUserReport{
  userreport='#submenu > :nth-child(9) > a',
  namereport=':nth-child(2) > .js-stools-column-order',
  usernamereport=':nth-child(3) > .js-stools-column-order',
  userwhatsappreport='#auctionUsersList > :nth-child(1) > tr > [width="10%"]',
  userbillnamereport='#auctionUsersList > :nth-child(1) > tr > :nth-child(5)',
  userbidcountreport=':nth-child(1) > tr > :nth-child(6)',
  userabsenteebidcountreport=':nth-child(1) > tr > :nth-child(7)',
  usergroupreport=':nth-child(8) > .js-stools-column-order',
  userselectgrpreport='#filter_group_id_chzn > .chzn-single > span',
  guestuserreport='#filter_group_id_chzn > div > ul > li:nth-child(3)',
  derivazuserrepo='#filter_group_id_chzn > div > ul > li:nth-child(6)',
  userregisteredreport='#filter_group_id_chzn > div > ul > li:nth-child(7)',
  bidderuserreport='#filter_group_id_chzn > div > ul > li:nth-child(11)',
  superuserreport='#filter_group_id_chzn > div > ul > li:nth-child(13)',
  userbidcount='[href="#userTotalBidModal-348"]',
  modalpopbidid='#userTotalBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(1)',
  modalpopbidamt='#userTotalBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(2)',
  modalpopbiddate='#userTotalBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(3)',
  modalpoplottitle='#userTotalBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(4)',
  modalpopauctiontitle='#userTotalBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(5)',
  modalpophighestbidmsg='#userTotalBidModal-348 > .modal-body > .row-fluid > .span12',
  modalpopclose='#userTotalBidModal-348 > .modal-footer > .btn',
  modalpopabsenteebidcount='[href="#userTotalAbsenteeBidModal-348"]',
  modalabsenteebidid='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(1)',
  modalabsenteebiamount='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(2)',
  modalabsenteebidate='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(3)',
  modalabsenteebilottitle='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(4)',
  modalabsenteeauctiontitle='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span8 > .table > thead > tr > th:nth-child(5)',
  modalpophighestabsenteebidmsg='#userTotalAbsenteeBidModal-348 > .modal-body > .row-fluid > .span12',
  modalpopabsenteebid='#userTotalAbsenteeBidModal-348 > .modal-footer > .btn',
  modalpopabsenteebidsecond='#userTotalAbsenteeBidModal-348 > .modal-footer > .btn'
}

export enum backendArticleCreation{
  contentmenu='#menu > li:nth-child(4) > a',
  articlemenu='#menu > li.dropdown.open > ul > li:nth-child(1) > a',
  contenttab='#myTabTabs > .active > a',
  imgandlinktab='#myTabTabs > :nth-child(2) > a',
  optiontab='#myTabTabs > :nth-child(3) > a',
  fieldtab='#myTabTabs > :nth-child(4) > a',
  homepageslidertab='#myTabTabs > :nth-child(5) > a',
  publishtab='#myTabTabs > :nth-child(6) > a',
  configeditscreentab='#myTabTabs > :nth-child(7) > a',
  permissiontab='#myTabTabs > :nth-child(8) > a',
  titleerror='.alert > div',
  articletitle='#jform_title',
  categorydropdown='#jform_catid',
  imgselect=':nth-child(1) > .controls > .field-media-wrapper > .input-prepend > .button-select',
  imgurl='#f_url',
  searchauctiondropdwn='#jform_com_fields_auctionid_chzn > .chzn-single > span',
  searchauction='#jform_com_fields_auctionid_chzn > div > div > input[type=text]',
  searchresultauc='.active-result > em',
  save='#toolbar-apply > .btn',
  startpublish='#jform_publish_up',
  createdate='#jform_created',
  user='userModal_jform_created_by.modal.hide.fade.in>div.modal-body>iframe>body.contentpane.component>div.container-popup>form#adminForm>div.js-stools.clearfix>div.clearfix>div.js-stools-container-bar>div.btn-wrapper.input-append>input#filter_search input',
  createby='.btn-primary',
  articlesearch='#filter_search',
  searchsymbolarticle='.input-append > .btn',
  cleararticlesearch='.js-stools-container-bar > :nth-child(4) > .btn',
  searchtoolarticle='.hidden-phone > .btn',
  selectstatustext='#filter_published_chzn > .chzn-single > span',
  selectlangtext='#filter_language_chzn > .chzn-single > span',
  selectmaxleveltext='#filter_level_chzn > .chzn-single > span',
  selectstatusdropdwn='#filter_published_chzn > .chzn-single > span',
  trashstatus='#filter_published_chzn > div > ul > li:nth-child(2)',
  unpublishstatus='#filter_published_chzn > div > ul > li:nth-child(3)',
  publishstatus='#filter_published_chzn > div > ul > li:nth-child(4)',
  archivestatus='#filter_published_chzn > div > ul > li:nth-child(5)',
  allstatus='#filter_published_chzn > div > ul > li:nth-child(6)',
  selectlanguagedropdwn='#filter_language_chzn > .chzn-single > span',
  alllanguage='#filter_language_chzn > div > ul > li:nth-child(2)',
  englishlanguage='#filter_language_chzn > div > ul > li:nth-child(3)',
  selectcatdropdwnarticle='#filter_category_id_chzn > .chzn-choices > .search-field > .default',
  selectcatactivetextbox='#filter_category_id_chzn > .chzn-choices > .search-field > .active',
  uncategorisedcat='#filter_category_id_chzn > div > ul > li:nth-child(1)',
  footerarticlecat='#filter_category_id_chzn > div > ul > li:nth-child(2)',
  newscat='#filter_category_id_chzn > div > ul > li:nth-child(3)',
  hompepageslidercat='#filter_category_id_chzn > div > ul > li:nth-child(4)',
  featuredcarouselcat='#filter_category_id_chzn > div > ul > li:nth-child(5)',
  regislidercat='#filter_category_id_chzn > div > ul > li:nth-child(6)',
  selectaccessdropdwnarticle='#filter_access_chzn > .chzn-choices > .search-field > .default',
  selectaccessactivetextbox='#filter_access_chzn > .chzn-choices > .search-field > .active',
  publicaccess='#filter_access_chzn > div > ul > li:nth-child(1)',
  guestaccess='#filter_access_chzn > div > ul > li:nth-child(2)',
  registeredaccess='#filter_access_chzn > div > ul > li:nth-child(3)',
  specialaccess='#filter_access_chzn > div > ul > li:nth-child(4)',
  superuseraccess='#filter_access_chzn > div > ul > li:nth-child(5)',
  selectauthordropdwn='#filter_author_id_chzn > .chzn-choices > .search-field > .default',
  selectauthoractivetextbox='#filter_author_id_chzn > .chzn-choices > .search-field > .active',
  priyankaauthor='#filter_author_id_chzn > div > ul > li:nth-child(2)',
  sayaliauthor='#filter_author_id_chzn > div > ul > li:nth-child(3)',
  sharayuathor='#filter_author_id_chzn > div > ul > li:nth-child(4)',
  tusharauthor='#filter_author_id_chzn > div > ul > li:nth-child(6)',
  selecttagdropdown='#filter_tag_chzn > .chzn-choices',
  selecttagdropdwnactive='#filter_tag_chzn > .chzn-choices > .search-field > .active',
  newstag='#filter_tag_chzn > div > ul > li:nth-child(1)',
  financetag='#filter_tag_chzn > div > ul > li:nth-child(2)',
  unpublisharticlebutton='#toolbar-unpublish > .btn',
  selectarticle='#cb0',
  publisharticlebutton='#toolbar-publish > .btn',
  alertmsgarticle='.alert-message',
  insertimgarticle='.modal-body > iframe',
  asertheader='#imageModal_jform_images_image_intro > .modal-header > h3',
  imgurltextbox='form#imageForm.form-horizontal>div.well>div.row-fluid>div.span12.control-group>div.controls>input#f_url',
  insertbutton='form#imageForm.form-horizontal>div.well>div.row-fluid>div.span4.control-group>div.pull-right>button.btn.btn-success.button-save-selected',
  saveandclosebtn='#toolbar-save > .btn',
  trasharticle='#toolbar-trash > .btn',
  createbyuserarticle='.btn-primary',
  assertselectuserheader='#userModal_jform_created_by > .modal-header > h3',
  searchboxarticle='form#adminForm>div.js-stools.clearfix>div.clearfix>div.js-stools-container-bar>div.btn-wrapper.input-append>input#filter_search',
  searchuserartilce='form#adminForm>div.js-stools.clearfix>div.clearfix>div.js-stools-container-bar>div.btn-wrapper.input-append>button.btn.hasTooltip',
  searchselectuserarticle='form#adminForm>table.table.table-striped.table-condensed>tbody>tr.row0:nth-child(1)>td>a.pointer.button-select',
  saveclosearticle='#toolbar-save > .btn',
  savenewarticle='#toolbar-save-new > .btn',
  cancelarticle='#toolbar-cancel > .btn',
  searcharticleclick='[href="/administrator/index.php?option=com_content&task=article.edit&id=62"]',
  slider='.active > div.ng-star-inserted > a.ng-star-inserted > .homepage-slide-container',
  homepagetitle='.active > div.ng-star-inserted > a.ng-star-inserted > .container > .pt-3 > .font-weight-bold',
  homepagenumber='.active > div.ng-star-inserted > a.ng-star-inserted > .container > .pt-3 > .fs-16',
  homepageAuctionDate='.active > div.ng-star-inserted > a.ng-star-inserted > .container > .pt-3 > .mb-0 > :nth-child(1)',
  homepageAuctionStatus='.active > div.ng-star-inserted > a.ng-star-inserted > .container > .pt-3 > .mb-0 > .link-blue'

}

